### PR TITLE
GitHub workflow to preview documentation changes/builds with example changes

### PR DESCRIPTION
**Pull request by sujaypatil96**
Testing fix for https://github.com/linkml/linkml/issues/2029

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Testing a fix for https://github.com/microbiomedata/nmdc-schema/issues/1588 here.

See original/current example deployed subset documentation page: https://microbiomedata.github.io/nmdc-schema/WorkflowSubset/

Compare with fixed subset documentation page here: https://microbiomedata.github.io/nmdc-schema/pr-preview/pr-2057/WorkflowSubset/

**Review by turbomam — APPROVED** [review]
theoretically could have been two PRs, but both aspects of this are **great**

**Comment by turbomam** [comment]
crazy speculative questions:

- what would happen if we had a schema element called `pr-preview`?
- do old previews ever get removed? if not , what are the costs of that?

**Comment by turbomam** [comment]
Please add the same thing to berkeley-schema-fy24 so we don't have to do a backmerege just for this

**Pull request merged**
