### PR TITLE
Issue #84 - add links for downloading data collections to README

### PR DESCRIPTION
**Pull request by turbomam**
Are you guys OK with the way I have exposed the NMDC JSON downloads (to the public?)

Please read the [two notes](https://github.com/microbiomedata/nmdc-schema/blob/issue-84/README.md#collections-within-the-schema).

### CODE REVIEW

**Comment by turbomam** [comment]
Please also see #76 . It would be nice to close or address both of these at the same time.

**Review by dwinston — CHANGES_REQUESTED** [review]
No, these are brittle links. I suggest we link to a timestamped [DRS *bundle*](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/#_drs_datatypes) that has, as its `contents`, a DRS *blob* for each bzipped json lines collection.

We can have a table of summary statistics, and we can also link directly to the DRS blob for each collection.

The link can be served from the nmdc-runtime dev deployment in the short term (https://api.nmdc-runtime-dev.polyneme.xyz/docs). We should get a nicer CNAME for this, e.g. api.microbiomedata.org.

**Review by wdduncan — APPROVED** [review]

**Comment by wdduncan** [comment]
I'll go ahead an merge.

**Comment by wdduncan** [comment]
Fixes #84

**Comment by turbomam** [comment]
In what ways are we still using DRS? Is it useful to end users, esp. now that we have metadata-download APIs?

**Comment by dwinston** [comment]
> Is it useful to end users...?
No idea. I have not been collecting usage logs. That would be step one.

**Comment by turbomam** [comment]
Would adding logging take much effort?

**Comment by dwinston** [comment]
shouldn't be too bad. can add a lightweight middleware to nmdc-runtime based on e.g. <https://github.com/tom-draper/api-analytics/tree/main/analytics/python/fastapi>.

**Pull request merged**
