### PR TITLE
Acknowledge two makefiles in README

### PR DESCRIPTION
**Pull request by turbomam**
sneak in edited README before EEC notices

continuation of
- #1168

### CODE REVIEW

**Review by eecavanna — APPROVED** [review]
Thanks!

**Review by eecavanna — COMMENTED** [review]
. (oops / ignore)

**Comment by eecavanna** [comment]
I'll request a review when I'm done making changes.

**Comment by turbomam** [comment]
Do you propose that the README defines all of the jargon we use, or just makefile-related jargon?

**Comment by eecavanna** [comment]
Hmm, I hadn't thought about that. Not necessarily all of the jargon (maybe top 5 concepts).

In this case, until this year, I hadn't used a Makefile for 10+ years and forgot the terminology (I don't know that I ever knew it). I thought others might be in the same boat and that the introductory sentence would ease them into the list that followed, which contained the term.

**Comment by eecavanna** [comment]
I'm ready for this branch to be reviewed/merged. I'll request a review here on GitHub.

**Review by eecavanna — APPROVED** [review]
I approve of my latest commits.

**Pull request merged**
