### PR TITLE
update source_mat_id

### PR DESCRIPTION
**Pull request by mslarae13**
update description, guidance, example, add todos

### CODE REVIEW

**Comment by turbomam** [comment]
Thanks, @mslarae13 . Are you going to specify what the `description`, `examples`, add `todos` should be?

LinkML doesn't have any concept of 'guidance'. DataHarmonizer composes the guidance from the `description` and the `comments`

**Comment by turbomam** [comment]
Great. I made some clerical changes in https://github.com/microbiomedata/nmdc-schema/pull/683/commits/c4ffd21175af1d779b7b0ad6e68d7ccd021dc570

**Review by turbomam — APPROVED** [review]

**Comment by mslarae13** [comment]
review completed with Mark

**Comment by mslarae13** [comment]
Completed checks with Mark

**Pull request merged**
