### PR TITLE
Integrate MIxS 6 submodule with nmdc-schema, make new import

### PR DESCRIPTION
**Pull request by turbomam**
## Goal
Update the MIxS integration in NMDC soon after Apr 28th release

@turbomam: minimize changed files. Give PR and issue a better name.

Not all of the reviewers are expected to pour over all of the changes.

---

See Issue #291 

- identify slots historically provided by `src/schema/mixs.yaml`
- also call out lost slots... are they really needed/used?
- import as many of those slots from MIxS 6, into a new YAML file

### CODE REVIEW

**Comment by turbomam** [comment]
This PR is mostly concerned with creating a new, dynamic MIxS import for the nmdc-schema. It would replace the mostly static MIxS 5-based `src/schema/mixs.yaml`

See these issue comments:
- https://github.com/microbiomedata/nmdc-schema/issues/291#issuecomment-1093003740
- https://github.com/microbiomedata/nmdc-schema/issues/291#issuecomment-1093031441

**Comment by turbomam** [comment]
This PR now includes all MIxS 6 slots used by all environmental packages in the NMDC DH schema. 

## Notes

- No packages have been curated except for soil. That means that there are probably slots in here that we may choose not to include
- Although the NMDC DH schema is examined to see what slots should be imported, the imports are taken from the MIxS schema itself, and do not include any modifications present in the NMDC DH schema.

**Comment by turbomam** [comment]
## Manual checks that should probably become tests 

https://github.com/microbiomedata/nmdc-schema/blob/issue-291-mixs-submod/src/schema/mixs_6_for_nmdc.yaml

- [ ] `EMSL`: omit, since it's a **dh_section**
- [ ] `gender_restroom`: yes, this is new for us (from built environment?) and should be included
- [ ] `source_mat_id`: include but without "globally unique ID" title

**Comment by sujaypatil96** [comment]
Reviewing this. Will add comments soon.

**Comment by sujaypatil96** [comment]
I'm reviewing this PR and the new submodule process, by running and testing the Makefile targets. Here is the list of commands that I ran one after the other:

```
git checkout -b issue-291-mixs-submod   # make sure you are on the right branch
poetry install   # install all necessary dependencies in a virtualenv

git submodule init   # initialize local configuration file
git submodule update   # fetch data from above project

make mixs_clean   # remove all mixs specific files
make reports/slot_roster.tsv   # class slot relationships from MIxS and NMDC
make src/schema/mixs_new.yaml   # NMDC specific new MIxS 6 YAML
```

The mixs_new.yaml file got generated successfully and replaced the old mixs.yaml.

**Review by sujaypatil96 — APPROVED** [review]

**Pull request merged**
