### PR TITLE
differentiate cookiecutter-help from help

### PR DESCRIPTION
**Pull request by turbomam**
- #1168

### CODE REVIEW

**Comment by eecavanna** [comment]
Thank you!

I recommend also putting a few lines in the `README.md` about the Makefiles. For example:

```md
# Makefiles

This repo contains 2 Makefiles:
- `Makefile`: (description...)
- `project.Makefile`: (description...)

How people can use the Makefiles: (including prerequisites and examples)
```

**Review by eecavanna — APPROVED** [review]

**Comment by eecavanna** [comment]
@turbomam, are you open to me adding a commit to this branch, that contains such a blurb in the README? I could do it during the 2-3pm PT hour.

**Comment by turbomam** [comment]
I just did it, but you can enhance it if you want

**Comment by turbomam** [comment]
digging up some evidence :-)

**Comment by turbomam** [comment]
I hadn't committed. Which means you still have an opportunity to improve the branch.

I asked for your review on 
- https://github.com/microbiomedata/nmdc-schema/pull/1213

**Pull request merged**
