### PR TITLE
Update database tools add search for orphaned data objects

### PR DESCRIPTION
**Pull request by mbthornton-lbl**
This PR provides:
- Add methods to API client to get Data Objects by Id or description
- Add option to extract_study to look for orphaned DO's

### CODE REVIEW

**Review by turbomam — COMMENTED** [review]
@mbthornton-lbl if you will add a `project.Makefile` target that illustrates the use of `--search-orphaned-data-object`, then I will test and presumably merge

**Comment by turbomam** [comment]
thanks

maybe I don't understand what it means for a record to be orphaned, and how retrieving orhaned records fits into the study-related retrieval task. I also thought that there was a parameter somewhere for specifying what description were to be searched for, but I may have skimmed too fast.

I'll check out and experiment today.

**Comment by turbomam** [comment]
Is the orphan searching compatible with the quick test mode?

**Comment by turbomam** [comment]
PS It still takes me 30 to 40 minutes to retrieve the records related to  most studies. I have a 250 Mbps connection, but it doens't look like it (or the CPU) is ever getting saturated

Do we now people who are using it besides you and me?

**Comment by mbthornton-lbl** [comment]
Added a description of "orphaned" Data Object in the script docs:
The search-orphaned-data-objects option is optional. This will search for
    data objects that are not referenced in has_output, but contain a workflow
    activity ID in their description. Default is to not search for orphaned
    data objects.

**Comment by mbthornton-lbl** [comment]
As far as time - in my hands I am getting:
`Extracted study nmdc:sty-11-aygzgv51 from the NMDC database in 0:09:15.061582.`

**Comment by turbomam** [comment]
> Extracted study nmdc:sty-11-aygzgv51 from the NMDC database in 0:27:32.033394.

Who do you think we could brainstorm on this with?

**Comment by turbomam** [comment]
I ran your target that includes `--search-orphaned-data-objects` and it completed. Maybe you could give me a walk-though of what records are included in that configuration that wouldn't have been in the default configuration? 

In any case, I approve, but we shouldn't merge until @pkalita-lbl's 2024.1 NMDC ecoystem release has been finished.

**Comment by mbthornton-lbl** [comment]
@turbomam are we still blocked from merging this?

**Pull request merged**
