### PR TITLE
Rename biosample_category_enum to follow naming standards

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
@turbomam I'd appreciate your green signal for the changes to `biosample_category_enum` before I make changes to other enums. I have touched many different files while renaming - is that okay or should I stick to just `nmdc.yaml`? Also, is `nmdc.owl.ttl` autogenerated or do I need to rename the enum in this file as well?

**Review by turbomam — APPROVED** [review]
Great, but I messed up! I forgot to tell you that the changes should only be made in `src/schema/`. Most of the files in `nmdc_schema/` are subject to regeneration **from** the `src/schema/` YAML files.

I'm going to merge this, but will do a `make all test` and push after that.

**Comment by turbomam** [comment]
The files in `project/` are also always regenerated by `make all`

**Comment by turbomam** [comment]
So it's good that you run `make all` as part of your testing. Just don't commit any YAML or JSON files in `nmdc_schema/` or anything in `project/`

**Comment by turbomam** [comment]
I'm going to merge but you can continue to work out of this branch and make more PRs

**Pull request merged**
