### PR TITLE
verified GOLD ID examples  for #233

### PR DESCRIPTION
**Pull request by turbomam**
move some examples to todos for #233

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
can you not just make a real example?

**Comment by turbomam** [comment]
> can you not just make a real example?

I don't know what the ids/URIs are supposed to look like for these identifiers. Where could I find some?

**Comment by cmungall** [comment]
just look on the data portal or on gold itself!

**Comment by wdduncan** [comment]
@turbomam Please update the changelog.

**Pull request merged**
