### PR TITLE
This PR decreases the minimum cardinality for `Pooling.has_input` to  1

### PR DESCRIPTION
**Pull request by turbomam**
down from 2

### CODE REVIEW

**Comment by turbomam** [comment]
which do we really want?

**Comment by turbomam** [comment]
@aclum this will be an easy issue and PR for me to close, if you feel confident about the minimum and or maximum number of inputs into a `Pooling` process.

**Comment by aclum** [comment]
@turbomam  Where is the example data driving this change? Conceptually sample does not go through pooling for a sequencing lab workflow unless there are at least two samples so I think we should leave the minimum cardinality as 2.

**Comment by turbomam** [comment]
@aclum this PR was opened at the end of August. I think we tried setting a minimum cardinality of three on `Pooling.has_input` and then found that there were some Neon `Pooling`s with only two inputs, so we just completely removed the minimum cardinality constraint. We can leave it off, or change the minimum cardinality to 1 or 2.

But I don't have any motivating data and would be happy to close this PR without merging if you think that's best.

**Comment by aclum** [comment]
@turbomam Am i reading the schema incorrectly? I read [this](https://github.com/microbiomedata/nmdc-schema/blob/9e4c58099b2fe064b6b08d3e24cfaf36458cbefb/src/schema/nmdc.yaml#L201C6-L201C31) as the minimum cardinality for slot has_input is currently enforced as 2 in the main branch of the nmdc schema for class Pooling.

**Comment by turbomam** [comment]
Sorry for dragging you into this, @aclum. Yes, I see what you mean and suggest that we just close this PR without merging.

**Comment by aclum** [comment]
@turbomam  agree

**Pull request closed without merging**
