### PR TITLE
removed # comments and most deprecated elements

### PR DESCRIPTION
**Pull request by turbomam**
also replaced commented-out textual MIxS `see_also`s with id-based `see_also`s

- #1321

### CODE REVIEW

**Review by brynnz22 — APPROVED** [review]
It looks good to me!

**Review by brynnz22 — COMMENTED** [review]
Oh sorry, it looks like some of the example data files need to be updated with has_credit_associations that use `applied_role`

**Comment by turbomam** [comment]
Thanks for the quick turnaround. I got ahead of myself and asked for review without waiting for the checks to finish. I fixed the example data and the build process completed locally. The checks are running again now.

**Comment by turbomam** [comment]
I'm also running `make make-rdf` to be certain that the MongoDB contents aren't using deprecated elements.

**Pull request merged**
