### PR TITLE
all values for all 5 GOLD path elements

### PR DESCRIPTION
**Pull request by turbomam**
- https://github.com/microbiomedata/submission-schema/issues/154

This extracts all values for each of the five elements of all GOLD ecosystem paths and creates a TSV file whose contents could be pasted into https://github.com/microbiomedata/submission-schema/blob/main/schemasheets/tsv_in/enums.tsv 

We should be able to move this into submission-schema and even automate the pasting if desired

The enums will be much larger now

see https://github.com/microbiomedata/nmdc-schema/blob/154-gold-ecosystem-pathway-enumerations-are-out-of-date/assets/gold_ecosystem_path_enumerations.tsv

See @pkalita-lbl's discussion of inter-column validation at
- https://github.com/microbiomedata/submission-schema/issues/154#issuecomment-1887741134

### CODE REVIEW

**Comment by pkalita-lbl** [comment]
Can I ask why this is here and not in `submission-schema`?

**Comment by turbomam** [comment]
> Can I ask why this is here and not in `submission-schema`?

No good reason. I was confused when I got started. I'll move the PR and its code into `submission-schema` tomorrow morning if you think its still worth pursuing (given you idea about eliminating the enums altogether.)

**Comment by mslarae13** [comment]
I don't think making all values for the 5 fields is what we want to do. We still want to limit / filter some of them. This has to build and follow the tree that the GOLD tree does: https://gold.jgi.doe.gov/ecosystemtree

So if I select "Aquatic" I can't select "Geologic" from the "Terrestrial" branch.

**Comment by pkalita-lbl** [comment]
I'm going to suggest closing this PR in favor of https://github.com/microbiomedata/submission-schema/pull/173

**Review by mslarae13 — APPROVED** [review]

**Comment by pkalita-lbl** [comment]
https://github.com/microbiomedata/submission-schema/pull/173 has been merged. Closing this one.

**Pull request closed without merging**
