### PR TITLE
Added images to README.md for #73

### PR DESCRIPTION
**Pull request by turbomam**
NMDC image may be too big

Still need to find newer/better? schema image **or** validate the current one.

### CODE REVIEW

**Comment by wdduncan** [comment]
@turbomam This PR failed the validation check. Given how long it has been open is it best to just close the PR at this point?

**Comment by turbomam** [comment]
> @turbomam This PR failed the validation check. Given how long it has been open is it best to just close the PR at this point?

Sure. I think @cmungall wanted be to add some images back into the `README.md` after some refactoring had cause broken image links.

The badges and slideshow link are good.

What do you think of adding an NMDC banner? I think I had on in this old PR, but it was awfully big.

**Comment by wdduncan** [comment]
I think the NMDC image is fine, although it might need to be reduced.

**Comment by turbomam** [comment]
I decided to include the image but not the "high level overview" diagram

**Pull request closed without merging**
