### PR TITLE
Issue330 update identifiers

### PR DESCRIPTION
**Pull request by mslarae13**
I added some identifier slots we've discussed and updated some descriptions.

Please review my changes & make sure everything still looks correct!

I did NOT add emsl_study_identifier because @turbomam  and I did that in a branch he had open.

### CODE REVIEW

**Comment by mslarae13** [comment]
#330

**Review by turbomam — COMMENTED** [review]
`make all` was failing in this branch because the slot `gold_study_identifiers` was defined in both `external_identifiers.yaml` (which uses the **schema** `id` https://microbiomedata/schema/external_identifiers) and in `nmdc.yaml`, which uses the `id` https://microbiomedata/schema

_Those schema `id`s need to be fixed up in another future branch._

I fixed the double definition in commit [3f46d86c07f62cc73d14efa1fbb665063f6632de](https://github.com/microbiomedata/nmdc-schema/pull/491/commits/3f46d86c07f62cc73d14efa1fbb665063f6632de) 

I still have to see what the merge conflict is regarding the main branch. Then I'll propose modifications to the `Biosample` class `description` . If that's acceptable, then we can merge this into main.

**Review by turbomam — COMMENTED** [review]
The merge won't be difficult.

I will also be removing the `structured_pattern` assertions

**Review by turbomam — COMMENTED** [review]
I think this would benefit from some spell checking, too

**Review by turbomam — APPROVED** [review]
great

**Pull request merged**
