### PR TITLE
Use newer version of `urllib3` to avoid moderate security bug

### PR DESCRIPTION
**Pull request by turbomam**
GitHub's dependabot recently [reported an issue](https://github.com/microbiomedata/nmdc-schema/security/dependabot/11) in the `urllib3` Python package upon which this project depends. According to dependabot, the issue is present in `urllib3` version 2.2.1, but not 2.2.2. In this branch, I ran `poetry update urllib3` to update `urllib3` to a version newer than 2.2.1, and committed the resulting `poetry.lock` file.

### CODE REVIEW

**Comment by eecavanna** [comment]
I'd rather not have a new direct dependency be introduced when the only reason it is being introduced is to specify that a specific version of it be installed (and it is otherwise a transitive dependency). With this approach, even if the direct dependencies switch to using something other than urllib3, `nmdc-scehma` will continue to "depend" on it.

**Comment by eecavanna** [comment]
I think you can instead run:
```shell
poetry update urllib3
```
> Source: https://python-poetry.org/docs/cli/#update

And then commit the resulting `poetry.lock` file.

**Comment by turbomam** [comment]
> I'd rather not have a new direct dependency be introduced when the only reason it is being introduced is to specify that a specific version of it be installed (and it is otherwise a transitive dependency). With this approach, even if the direct dependencies switch to using something other than `urllib3`, `nmdc-schema` will continue to "depend" on it.

make sense @eecavanna. can you suggest an alternative?

**Comment by eecavanna** [comment]
> can you suggest an alternative?

I posted a shell command (suggestion) right above your most recent comment (I think we posted those at roughly the same time).

**Review by eecavanna — APPROVED** [review]

**Comment by eecavanna** [comment]
@turbomam, here's what I suggest for a PR description:

> GitHub's "dependabot" recently [reported an issue](https://github.com/microbiomedata/nmdc-schema/security/dependabot/11) in the `urllib3` Python package upon which this project depends. According to "dependabot," the issue is present in `urllib3` version 2.2.1, but not 2.2.2. In this branch, I ran `poetry update urllib3` to update `urllib3` to a version newer than 2.2.1, and committed the resulting `poetry.lock` file.
>
> This branch does not contain any schema changes.

**Review by mslarae13 — COMMENTED** [review]
@eecavanna approved, and I'll defer to him.

**Pull request merged**
