### PR TITLE
NMDC schema slots to NCBI MIxS term matching

### LINKED ISSUE #1940: Create declarative mapping file for NMDC-to-NCBI push
Similar to the "NCBI Postgres database column to NMDC slot names" mapping file that we have in `nmdc-schema`: https://github.com/microbiomedata/nmdc-schema/blob/main/assets/ncbi_mappings/ncbi_pg_db_field_mappings_filled.tsv already, we need another declarative mapping file that maps "NMDC slot names to all NCBI BioSample harmonized names".

The NCBI BioSample Attributes XML file can be found here: https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/

The declarative mapping file, which will also be a TSV file similar to _ncbi_pg_db_field_mappings_filled.tsv_ will map NMDC schema slots (from classes Biosample, Extraction, LibraryPreparation, OmicsProcessing, DataObject) to values in the harmonized_name/synonym/title column from the above table. Since the range of some of the measurement slots in NMDC schema follow an object pattern (as opposed to scalar values in NCBI and MIxS) we need to compose the slots using the dot notation on slots.

Example:

| nmdc_schema_class | nmdc_schema_slot | nmdc_schema_slot_range | ncbi_biosample_attribute_name | static_value | ignore |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Biosample | depth | QuantityValue | depth | |

Generic handling for nested data types in NMDC schema (to compose flat NCBI BioSample field values):
* QuantityValue
  * {slot_name}.has_numeric_value {slot_name}.has_unit, or
  * ( {slot_name}.has_maximum_numeric_value - {slot_name}.has_minimum_numeric_value ) {slot_name}.has_unit, or
  * <s>{slot_name}.has_raw_value</s>
* TextValue
  * {slot_name}.has_raw_value
* TimestampValue
  * {slot_name}.has_raw_value
* ControlledTermValue
  * {slot_name}.term.name [{slot_name}.term.id] , or
  * {slot_name}.term.id, or
  * {slot_name}.term.name, or
  * <s>{slot_name}.has_raw_value</s>
* ControlledIdentifiedTermValue
  * {slot_name}.term.name [{slot_name}.term.id], or
  * <s>{slot_name}.has_raw_value</s>
* GeolocationValue
  * {slot_name}.latitude {slot_name}.longitude, or
  * <s>{slot_name}.has_raw_value</s>

_{slot_name}_ is the name of a slot in the NMDC schema.

Note: This is the first of a series of tasks that need to be completed in order to address https://github.com/microbiomedata/nmdc-runtime/issues/503

### PR DESCRIPTION
**Pull request by sujaypatil96**
Fixes #1940

### CODE REVIEW

**Comment by sujaypatil96** [comment]
This PR is ready to be reviewed/merged.

**Comment by sujaypatil96** [comment]
Running the below command:

```zsh
nmdc-schema git:(issue-1940) ✗ nmdc-ncbi-mapping package-specific-curation assets/ncbi_mappings/ncbi_attribute_mappings_filled.tsv
Optional NCBI Attribute names that do not have NMDC slot mappings: ['collection_method', 'isolation_source', 'neg_cont_type', 'omics_observ_id', 'pos_cont_type', 'ref_biomaterial', 'rel_to_oxygen', 'samp_collect_device', 'source_material_id']
```

Manual mappings for the above slots that can be filled out:

| NCBI Attribute name | NMDC schema slot (mapped manually) |
| --------------------- | --------------------------------------- |
| collection_method | [samp_collec_method](https://microbiomedata.github.io/nmdc-schema/samp_collec_method/) |
| isolation_source | `MAN_IGNORE` |
| neg_cont_type | `MAN_IGNORE` |
| pos_cont_type | `MAN_IGNORE` |
| ref_biomaterial | [nucleic_acid_sequence_source_field](https://microbiomedata.github.io/nmdc-schema/nucleic_acid_sequence_source_field/) |
| rel_to_oxygen | [oxy_stat_samp](https://microbiomedata.github.io/nmdc-schema/oxy_stat_samp/) |
| samp_collect_device | [samp_collec_device](https://microbiomedata.github.io/nmdc-schema/samp_collec_device/) |
| source_material_id | [id](https://microbiomedata.github.io/nmdc-schema/id/) |

**Comment by sujaypatil96** [comment]
@turbomam requesting for a review on this PR. I suggest merging this in, and I will add my suggestions from the above comment to https://github.com/microbiomedata/nmdc-schema/blob/issue-1940/assets/ncbi_mappings/ncbi_attribute_mappings_filled.tsv once it has been created in `main`.

**Comment by turbomam** [comment]
do you still want this merge in here, as opposed to nmdc-runtime?

**Comment by turbomam** [comment]
I guess so since they are changes and not additons

**Review by turbomam — APPROVED** [review]

**Pull request merged**
