### PR TITLE
Refactor migrator classes into own modules and fix YAML file loading

### PR DESCRIPTION
**Pull request by eecavanna**
### Summary

- Created a new package named `migrators` that contains the migration-specific classes
- Moved `MigratorBase` class from `migration_recursion.py` into its own module within the `migrators` package
- Moved each migration-specific class from `migration_recursion.py` into its own module within the `migrators` package
- Moved a YAML file used by one migration-specific class into a new `assets/` directory within the `migrators` package
- Moved CURIE-related helper functions directly called by `migration_recursion.py` into a new `CurieMigrator` class
- Removed the unused `force_prefix` property from the `MigratorBase` class (it still exists on the `CurieMigrator` class)
- Capitalized names of regex pattern "constants" per [PEP 8](https://peps.python.org/pep-0008/#constants) style guide
- Configured Poetry so consumers of the PyPI package can `import` things residing in `nmdc_schema/migrators/` (instead of only things residing at the top level of `nmdc_schema/`).
    - I tested this new configuration by running `pip install /path/to/local/clone/of/nmdc-schema` and confirming the following `import` statement worked:
      ```py
      from nmdc_schema.migrators.migrator_from_8_1_to_9_0 import Migrator_from_8_1_to_9_0 as Migrator
      ```
     - I did **not** test it on PyPI (I did not publish anything to PyPI)
- Fixed bug where, in general, a YAML file could not be loaded except for in the `nmdc-schema` development environment
    - Bug: https://github.com/microbiomedata/nmdc-schema/issues/1310

### CODE REVIEW

**Comment by eecavanna** [comment]
I finished refactoring the migration-related classes into a subfolder. 

✅ I confirmed that the `migration_recursion.py` script still runs without error. For example, this runs without error:
```shell
poetry run migration-recursion \
  --salvage-prefix nmdc \
  --output-path /tmp/output.yaml \
  --schema-path nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml \
  --input-path local/mongo_as_unvalidated_nmdc_database.yaml \
  -v DEBUG \
  --migrator-name Migrator_from_8_1_to_9_0
```

🔥 However, since making these changes, I have **not** been able to `import` any of the migration-related classes (no longer defined in `migration_recursion.py`) from a Python notebook in `nmdc-runtime` (from which I had been able to import the classes before making these changes). 

I have tried several things in an attempt to be able to `import` them, but none of the things I tried worked. You can see the things I tried in the commits that begin with `WIP:` (all of which have since been reverted).

Note: Since making these changes, I have only tried installing the package via **GitHub** (via the command below). Maybe the `import` issue is related to the fact that the code in this branch is "source" code, as opposed to something "built" by Poetry.

```shell
pip install git+https://github.com/microbiomedata/nmdc-schema.git@1250-move-each-migration-class-into-its-own-module-in-a-migrations-folder
```

**Comment by eecavanna** [comment]
In case this PR is still open on Tuesday, I can present the changes during the migration squad meeting that day.

**Review by brynnz22 — COMMENTED** [review]
@eecavanna this looks great to me! A lot easier to digest and understand than one big file. I'll let @turbomam approve this since he knows the structure of the repo much better than me. Is there a way we can include dumping the output of a migration(s) into a yaml file as we did with the `migration_recursion.py` file so that we can test the migrations while writing them?

**Comment by eecavanna** [comment]
Thanks, @brynnz22! The `migration_recursion.py` script still behaves the same way (from the outside) that it does in the current `main` branch; i.e. it can still be used to migrate data residing in a YAML file. Does that answer your question?

---

On a side note about testing, after this branch has been merged in, I'm planning to add some `doctests` to the transformation functions (https://github.com/microbiomedata/nmdc-schema/issues/1291). I'll add a note to tomorrow's squad meeting agenda to demonstrate doctests.

**Comment by eecavanna** [comment]
@eecavanna : Emphasize in click help that the class name is NOT the module name / filename.

@eecavanna : Emphasize X.Y as default instead of X.Y.Z for migrations.

**Comment by eecavanna** [comment]
I updated the `click` command help. Here's a snippet from the latest help:

```plain
  --migrator-name TEXT   The name of a migrator class (i.e. a class that
                         inherits from `MigratorBase`) that you want to use to
                         migrate data.
                         
                         Those classes are defined in `nmdc_schema/migrators/`
                         and their names begin with `Migrator_`. If you
                         specify this option multiple times, the specified
                         classes will be used in the order specified.

```

**Comment by eecavanna** [comment]
Hi @turbomam, I finished making one of the [changes](https://github.com/microbiomedata/nmdc-schema/pull/1340#issuecomment-1811127872) we discussed in today's pair review. I want to hold off on the other one until a future PR, where I make other changes to the documentation and example migrator class.

**Review by turbomam — APPROVED** [review]

**Pull request merged**
