### PR TITLE
COC 2024

### PR DESCRIPTION
**Pull request by shreddd**
Updated the Code of Conduct based on NMDC staff feedback. Ready to merge.

### CODE REVIEW

**Review by lamccue — APPROVED** [review]
Looks great.

**Review by emileyfadrosh — APPROVED** [review]
Thanks, looks great!

**Comment by turbomam** [comment]
Yes, this is very good. 

At one point, we had at least one document that combined these messages of honoring diversity with more procedural messages like "Stick to a meetings agenda as much as possible! Write meaningful commit messages!" Where's the best place for that kind of thing now?

**Comment by ssarrafan** [comment]
> Yes, this is very good.
> 
> At one point, we had at least one document that combined these messages of honoring diversity with more procedural messages like "Stick to a meetings agenda as much as possible! Write meaningful commit messages!" Where's the best place for that kind of thing now?

How about keeping some **ground rules** in a Google doc or here in GitHub for these kinds of things. Here is a draft related to meetings: 

1. Clear agenda, sent out 1 day before meeting if possible
2. Introduce, welcome new members
3. Don't interrupt people speaking, use the hands-up feature on zoom
4. Shared documentation/notes for other team members and for future, help document decisions needed or made in the notes and/or decision log or in an ADR in GitHub
5. Review next steps, action items in notes and at the meeting
6. Schedule meetings for 50 or 55 minutes to allow a break between meetings, end meetings on time

@turbomam is this what you had in mind? 

FYI @shreddd @emileyfadrosh

**Pull request closed without merging**
