### PR TITLE
#256 slot report

### PR DESCRIPTION
**Pull request by turbomam**
gets saved to the local dir. could put in an assets dir instead. have published one time at https://docs.google.com/spreadsheets/d/1yTCqZojqoLPa0Y97ZYcyFuEG-u-oXf7OSCvq9Hu4dCQ/edit#gid=0

### CODE REVIEW

**Comment by turbomam** [comment]
could also do a long format, and include a 'preferred replacement value' column. For example, I think there is an interest in using slot usage to assign a description value of 'a human-readable description of a thing'  to the description  slot on the study class.

**Comment by wdduncan** [comment]
@turbomam I'm not sure what you mean by using `slot_usage`. You can override the descriptions for slots (of course), but I do not think you can override descriptions for classes (I could do this locally). Perhaps you make use of the [alt_descriptions](https://linkml.io/linkml-model/docs/alt_descriptions/) slot?

Also, can you open up access to the google sheet to anyone with a link?

**Comment by turbomam** [comment]
> I do not think you can override descriptions for classes (I could do this locally). Perhaps you make use of the [alt_descriptions](https://linkml.io/linkml-model/docs/alt_descriptions/) slot?

yes, good points @wdduncan

**Comment by turbomam** [comment]
> can you open up access to the google sheet to anyone with a link?

I opened it up for viewing to `anyone with a link`. Did you want it world editable @wdduncan ?

**Comment by wdduncan** [comment]
@turbomam I was thinking it would be helpful if anyone with a link could view the google sheet.

**Pull request closed without merging**
