### PR TITLE
`type` slot assertion on planned NEON process classes and processed sample

### LINKED ISSUE #1027: Add type on class `PlannedProcess`
Children of class [PlannedProcess](https://microbiomedata.github.io/nmdc-schema/PlannedProcess/) (Pooling, Extraction, LibraryPreparation) are being used extensively in the NEON metadata ingest pipeline to create instances of above mentioned processes.

It is useful to know the _type_ of instances being created, like how we indicate for _Biosamples_ that they are of type `nmdc:Biosample`. Similarly, it is useful to annotate instances of PlannedProcess objects (and their children) with type as well. For example, Pooling process instances will have type `nmdc:Pooling`, Extraction process instances will be of type `nmdc:Extraction` and so forth. This is useful redundancy to have, because it helps while writing queries against the database.

So we are requesting a modeling change where you assert the slot [type](https://microbiomedata.github.io/nmdc-schema/type/) on PlannedProcess, which will carry over into its child classes as well.

### PR DESCRIPTION
**Pull request by sujaypatil96**
Fixes #1027 and #1030

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Agenda item for 8/16 call with @turbomam:

- decide how we want to constrain the _range_ of type slot on the NEON PlannedProcess and ProcessedSample classes.

**Comment by aclum** [comment]
@turbomam  can we get this reviewed and merged? @sujaypatil96  is there corresponding migration code?

**Comment by turbomam** [comment]
This can be closed, but we need to refactor "type" slots ASAP. I have an issue for this but haven't found it yet.

**Comment by aclum** [comment]
@turbomam  are you saying you'd like to close instead of merge this pull request where @sujaypatil96  has addressed some of the type slot issues?

**Comment by turbomam** [comment]
I was hoping to 
- prioritize applying `type`, as an inherited type-designating slot (whose range would be identifiers of nmdc-schema classes) to root classes
- remove all other NMDC slots with "type" in their name. (We would keep any MIxS slots that ahve "type" in the name)

**Comment by aclum** [comment]
If we can address your first bullet 'prioritize applying type, as an inherited [type-designating slot](https://linkml.io/linkml/schemas/type-designators.html) (whose range would be identifiers of nmdc-schema classes) to root classes' with the december refactor we should do that in favor on merging this in. let's leave this open until we decided @lamccue @mslarae13

**Comment by mslarae13** [comment]
I'll defer to @lamccue for the prioritization & if there's time to target `type` for December. 

As for getting it done, @turbomam can we get a list of all the slots that have "type" in the name/title that shouldn't so we can evaluate how many slots we need to change?

**Comment by lamccue** [comment]
I don't have a good understanding of the level of effort required, or the impact the change would have within the schema, of the first point, i.e.,: 

1. prioritize applying type, as an inherited [type-designating slot](https://linkml.io/linkml/schemas/type-designators.html) (whose range would be identifiers of nmdc-schema classes) to root classes

**Comment by aclum** [comment]
Just a note that we can separate concerns here wrt to what gets done during the December refactor, we can add slot 'type' on all classes and set a range to be a class independent of changing the name of slots which currently have the word type in them (ie data_object_type).

**Comment by aclum** [comment]
Im going to close this PR since @turbomam took care of what is addressed in this PR globally in the berkeley-schema-fy24 fork. I unlinked the nmdc-schema ticket so that would remain open.

**Pull request closed without merging**
