### PR TITLE
2270 model amplicon data

### PR DESCRIPTION
**Pull request by aclum**
This PR adds minimal modeling to support amplicon data. This is in support of milestone 2.5 which is to add new data types.

### CODE REVIEW

**Comment by aclum** [comment]
@turbomam @sierra-moxon  I need help here. src/data/valid/NucleotideSequencing-amplicon.yaml passes when i run it locally but not via the automated tests.

```
poetry run linkml-validate -C NucleotideSequencing -s nmdc_schema/nmdc_materialized_patterns.yaml src/data/valid/NucleotideSequencing-amplicon.yaml
No issues found
```

**Comment by aclum** [comment]
Mark and I met briefly and discussed
- text value vs enumeration for value of target_gene
- if we should move target_gene and target_subfragment to LibraryPreparation

**Comment by aclum** [comment]
@pkalita-lbl Anything else needed in this PR to make 'Amplicon sequencing assay' available in the submission schema and therefore the submission portal that what I've already done.

**Comment by pkalita-lbl** [comment]
> Anything else needed in this PR to make 'Amplicon sequencing assay' available in the submission schema and therefore the submission portal that what I've already done.

I don't believe so, once this change goes into a new released schema version a new version of `nmdc-submission-schema` can be built off that and will inherit the new permissible value.

I think the reason that the test is failing is that your examples in `src/data/valid/Biosample-amplicon.yaml` and `src/data/valid/NucleotideSequencing-amplicon.yaml` define _lists_ of objects (well, lists of one object anyway) because of the ` - ` before `id`. I believe `linkml-run-examples` is expecting you to define one single object in the YAML file. `linkml-validate` is a little more forgiving and will validate each item in a YAML list individually if that's what you give it.

**Comment by turbomam** [comment]
trying this PR now

**Comment by turbomam** [comment]
@aclum and I have introduced `TargetGeneEnum` as the range for `target_gene`. `target_gene` is a MIxS slot, and mixy.yaml is subject to regeneration, so it should not be edited directly. See `local/mixs_regen/mixs_subset_modified_inj_TargetGeneEnum.yaml` in `project.Makefile`

That's a perpetuation of a free-standing schema modification trick that @pkalita-lbl and I hope to add to sheets_and_friends eventually.

regeneration of `mixs.yaml` requires:

```shell
rm -rf src/schema/mixs.yaml
make squeaky-clean mixs-yaml-clean
make src/schema/mixs.yaml
```

after which the mixs.yaml should be committed

**Review by turbomam — APPROVED** [review]
I approve provided the only other changes before merging are additions of permissible values to the TargetGeneEnum.

I contributed to this PR, so at least one other approver would be prudent

**Review by sierra-moxon — APPROVED** [review]

**Pull request merged**
