### PR TITLE
Refactor `LabDevice`, `Instrument` and `InstrumentValue`

### PR DESCRIPTION
**Pull request by turbomam**
- #1331 

will add similar classes in in subsequent commit

### CODE REVIEW

**Comment by JamesTessmer** [comment]
These look good to me, but I'd also like to see if everyone agrees before approving.

**Comment by JamesTessmer** [comment]
> 

Oops, I misread the 'added as reviewer' email as 'ready for review'

**Comment by turbomam** [comment]
I should add an example of some `PlannedProcess` instance relating to a named or anonymous instrument. The relating slot would use some language like "used", but not `used`, because that has an incompatible `range`.

**Comment by anastasiyaprymolenna** [comment]
We need to include more permissible values in the instrument enums. See this commit for the sample processing enums https://github.com/microbiomedata/nmdc-schema/commit/b2e8c21ad57d8b9c769ed66d678749ab2d2853b3

**Comment by turbomam** [comment]
better names for NamedInstrument:
- analytical instrument?
- data generating instrument

**Comment by turbomam** [comment]
what kinds of things can have a relationship with XInstruments, via what slots?

not `used`

**Pull request merged**
