### PR TITLE
NCBI BioSample attributes/NMDC schema slots mapping file - exact term matching

### PR DESCRIPTION
**Pull request by sujaypatil96**
Add TSV file described in issue #1795 to start fleshing out a mapping file between NCBI BioSample attributes and NMDC schema slots.

CC: @turbomam

### CODE REVIEW

**Comment by sujaypatil96** [comment]
I have not pushed up any code/updates to the mapping file yet, but I do have changes/updates on my local machine that I wanted to discuss with you first before pushing it up. We can talk about that tomorrow, 3/11.

**Comment by turbomam** [comment]
Looking forward to reviewing your work!

**Comment by turbomam** [comment]
The exact mapping to NCBI term names and synonyms are great, but the fuzzy matches aren't actionable. As discussed, I recommend using a LLM.

**Comment by sujaypatil96** [comment]
@turbomam I have pushed up the code for exact term matching between NMDC schema slots and NCBI postgres db view field/column names.

**Comment by sujaypatil96** [comment]
I have re-titled this PR to indicate that it has mappings from exact term matching. This PR is good to be merged in after your review. We can make another PR for the LLM based matching strategy.

**Review by turbomam — APPROVED** [review]

**Pull request merged**
