### PR TITLE
Rename enums per naming standards

### LINKED ISSUE #931: work on enum and permissible value names/texts
- match the case expected by the linter, https://linkml.io/linkml/schemas/linter.html#standard-naming
- don't use any characters that are illegal in URLs or require excessive escaping: https://docs.microfocus.com/OMi/10.62/Content/OMi/ExtGuide/ExtApps/URL_encoding.htm

### PR DESCRIPTION
**Pull request by Shalsh23**
This PR specifically addresses enums in `src/schema`, including `src/schema/portal`, but not including `src/schema/mixs.yaml`, and updates the names/keys of enums to be `PascalCase/UpperCamelCase` in compliance with [schema naming standards](https://linkml.io/linkml/schemas/linter.html#standard-naming ).

Closes #931

### CODE REVIEW

**Comment by Shalsh23** [comment]
@turbomam These seem to be the entirety of enums that needed to be renamed in the `src/schema`.

**Review by turbomam — APPROVED** [review]
Awesome. I got an alert that you sent me a message that seemed to be a discussion of this PR, but I haven't read it yet.

Have you run the resulting schema through the `linkml-linter`? That will confirm if all enums are cased properly. It will also complain about other things which we can deal with later. I think there is a rule for running the linter in the `Makefile` or the `project.Makefile`. 

How did you feel about this task? Does it give you a sense of other ways in which you'd like to contribute?

**Comment by turbomam** [comment]
Here are some possible follow-up actions for this PR. It's a mixture of software engineering and social engineering. 

_I kinda got onto a roll with brainstorming. The two of us could talk in person soon, you could ask for a second opinion form other people, or just tell me that I'm crazy._

1. We will need to communicate these changes to anybody who adds data to MongoDB under one of the legacy enums. I have a suspicion that they just hard code the legal values into their applications, whereas they should be dynamically getting them from the schema. I guess most of these people and tools are at least checking the data objects against the schema in some way or another before inserting it. Exhaustive checking would include instantiating their data as nmdc-schema classes and checking them with json-schema.
2. In addition to working the permissible value keys/texts, we should be improving the schema by adding annotations to the [enumerations](https://linkml.io/linkml-model/docs/EnumDefinition/) and the [permissible values.](https://linkml.io/linkml-model/docs/PermissibleValue/) That will require gathering input form the enumeration stakeholders. Maybe we should start looking through the nmdc-runtime code to see where people are invoking the enumerations.
3. LinkML has a concept of dynamic enumerations, where the permissible values are not provides, but a [path to the values](https://linkml.io/linkml-model/docs/reachable_from/) is provided in the context of an ontology graph. Have you come across that yet? I don't think it's fully implemented yet. We could start using that to express something like EnvBroadScalesForSoil. You'll see that some guidelines are provided for choosing EnvO terms for the `env_broad_scale` slot, but it is not broken down into reasonable values on an environment basis, like water vs soil.

For 3. above, several NMDC people have already put some in effort, mostly in manual curation or supervised ML-based category prediction. I have also worked on solutions that traverse the EnvO with the SAPRQL query language. I think the ultimate solution may come from the ChatGPT API. So we really need to review our ideas with @cmungall , @shreddd  and others.

**Comment by cmungall** [comment]
Remember to follow best practice, PRs should have a description, they should be linked to an issue, etc

**Comment by turbomam** [comment]
Thanks for the recent commits, @Shalsh23 

We just had the NMDC metadat/schema, which included a good conversation about best practices for schema issues, branches, PRs and releases

I'd like to use this work of yours as a test case for that, because the changes you made follow best schema practices, but we may have to coordinate with other stakeholders. Most people address the **slots** that have enumerated values instead of addressing the **enumeration names** directly, but we should check.

No action required from you yet!

**Comment by Shalsh23** [comment]
> Thanks for the recent commits, @Shalsh23
> 
> We just had the NMDC metadat/schema, which included a good conversation about best practices for schema issues, branches, PRs and releases
> 
> I'd like to use this work of yours as a test case for that, because the changes you made follow best schema practices, but we may have to coordinate with other stakeholders. Most people address the **slots** that have enumerated values instead of addressing the **enumeration names** directly, but we should check.
> 
> No action required from you yet!

Thanks for the update @turbomam , and my apologies for the delay in responding. I think I would also need a meeting with you to better understand your suggestions regarding follow-up items for this PR. I'll go ahead and put something on your calendar.

**Comment by mslarae13** [comment]
@turbomam @Shalsh23 can we merge this in?

**Comment by mslarae13** [comment]
@Shalsh23  @turbomam  can we get this merged in? It's blocking Update list of sample types available in EMSL submission context shipping form
[#600](https://github.com/microbiomedata/issues/issues/600) for the UFO squad. I'd like to move forward.

**Comment by Shalsh23** [comment]
> @Shalsh23 @turbomam can we get this merged in? It's blocking Update list of sample types available in EMSL submission context shipping form [#600](https://github.com/microbiomedata/issues/issues/600) for the UFO squad. I'd like to move forward.

Hey Montana, sorry I missed your earlier message. I am/have been on leave for the past few weeks. This PR is ready to merge from my end and I'll let @turbomam review and proceed with the merging of this PR.

**Review by turbomam — APPROVED** [review]

**Pull request merged**
