### PR TITLE
Add a `Sample` grouping class in order to remove `any_of` range constraints

### PR DESCRIPTION
**Pull request by sierra-moxon**
First PR towards removing `any_of` range constraints.
`Sample` is currently a grouping class for `ProcessedSample` and `Biosample` and is abstract.

### CODE REVIEW

**Comment by turbomam** [comment]
This is going to be great @sierra-moxon 

Is there any connection with 
- https://github.com/microbiomedata/nmdc-schema/pull/2246

**Review by eecavanna — COMMENTED** [review]
This looks good to me, @sierra-moxon. Thanks for implementing it (and walking us through it during today's meeting). The only thing I'm hesitant about is that the only `is_a` field that was modified here is for the `Biosample` class. Did you mean to do the same thing to the `ProcessedSample` class?

**Comment by sierra-moxon** [comment]
> This looks good to me, @sierra-moxon. Thanks for implementing it (and walking us through it during today's meeting). The only thing I'm hesitant about is that the only `is_a` field that was modified here is for the `Biosample` class. Did you mean to do the same thing to the `ProcessedSample` class?

Hi @eecavanna! :) can you check the is_a hierarchy here again?  -- I appreciate your review.

**Comment by sierra-moxon** [comment]
@turbomam - just a ping to say this is ready for review.

**Review by turbomam — APPROVED** [review]

**Comment by eecavanna** [comment]
Here's a summary of my takeaways from reading the latest diff:
1. The `DataGeneration` class's `has_input` slot used to have an `any_of` constraint defined (whose members were: `- range: Biosample` and `- range: ProcessedSample`). This PR removes that `any_of` constraint and replaces it with `range: Sample`.
2. The same is true about the `MaterialProcessing`, `Extraction`, `SubSamplingProcess`, `MixingProcess`, `FiltrationProcess`, and `ChromatographicSeparationProcess` classes.
3. This PR introduces a `Sample` class, which `is_a: MaterialEntity`.
4. The `Biosample` class used to have `is_a: MaterialEntity` on it. This PR replaces that with `is_a: Sample`.

**Review by eecavanna — APPROVED** [review]

**Pull request merged**
